FROM node:16-alpine as base

FROM base as compiler

WORKDIR /usr/app

COPY package*.json .
COPY src src
COPY tsconfig.json tsconfig.json

RUN npm install

RUN npx tsc

RUN npm prune --production --verbose

FROM base as worker

WORKDIR /usr/app

COPY --from=compiler /usr/app/build build
COPY --from=compiler /usr/app/package.json package.json
COPY --from=compiler /usr/app/node_modules node_modules

CMD [ "node", "build/start.js" ]