FROM node:16-alpine

WORKDIR /usr/app

COPY package*.json .
COPY src src
COPY tsconfig.json tsconfig.json

RUN npm install

RUN npx tsc

RUN rm -rf node_modules
RUN rm -rf src

RUN npm install --prod
RUN npm cache verify
RUN npm cache clean --force

CMD [ "node", "build/start.js" ]