FROM node:16-alpine as base

FROM base as builder

WORKDIR /usr/app

RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls

FROM base as worker

RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls
RUN ls

CMD [ "ls" ]